# version: 2.1

# executors:
#   default:
#     working_directory: ~/lms
#     docker:
#       - image: circleci/ruby:2.6.3
#         environment:
#           BUNDLE_JOBS: 3
#           BUNDLE_PATH: vendor/bundle
#           BUNDLE_RETRY: 3
#           BUNDLER_VERSION: 2.0.1
#           RAILS_ENV: test
#           DB_HOST: 127.0.0.1
#           PG_HOST: 127.0.0.1
#           PGUSER: lms_test
#       - image: circleci/postgres:10.15
#         environment:
#           POSTGRES_DB: lms_test
#           POSTGRES_USER: lms_test

# commands:
#   configure_bundler:
#     description: Configure bundler
#     steps:
#       - run:
#           name: Configure bundler
#           command: |
#             echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
#             source $BASH_ENV
#             gem install bundler

# jobs:
#   build:
#     executor: default
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - lms-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - lms-
#       - configure_bundler
#       - run:
#           name: Install bundle
#           command: bundle install
#       - run:
#           name: Wait for DB
#           command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
#       - run:
#           name: Setup DB
#           command: bundle exec rails db:create db:schema:load --trace
#       - save_cache:
#           key: lms-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle
#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - ./lms

#   done:
#     docker:
#       - image: circleci/ruby:2.6.3
#     executor: ruby/default
#     steps:
#       - curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"


# workflows:
#   version: 2
#   integration:
#     jobs:
#       - build
#       - done:
#         requires: build



version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: lms_test
      - image: circleci/postgres:10.15
        environment:
          POSTGRES_DB: lms_test
          POSTGRES_USER: lms_test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install new bundler
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: yarn install
      - run: bundle exec rails db:schema:load --trace
      - run:
          name: Tests
          command: bundle exec rspec


  done:
    docker:
      - image: circleci/ruby:2.6.3
    executor: ruby/default
    steps:
      - curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"
