version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install new bundler
          command: gem install bundler:2.1.4
      - run:
          name: update bundler
          command: bundle update --bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

notify:
  webhooks:
    - url: htpps://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
